// Supabase client configuration
import { createClient, SupabaseClient } from '@supabase/supabase-js';

// TODO: Generate proper types with: supabase gen types typescript --local
// For now, using any to avoid type issues
type Database = any;

let supabaseClient: SupabaseClient<any> | null = null;
let useInMemory = false;

export function getSupabaseClient(): SupabaseClient<any> | null {
  if (supabaseClient) {
    return supabaseClient;
  }

  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.warn('⚠️  Supabase credentials not found - using IN-MEMORY storage');
    console.warn('⚠️  Data will be lost on server restart!');
    useInMemory = true;
    return null;
  }

  try {
    supabaseClient = createClient(supabaseUrl, supabaseKey, {
      auth: {
        persistSession: false, // For server-side usage
        autoRefreshToken: false,
      },
    });

    console.log('✅ Connected to Supabase');
    return supabaseClient;
  } catch (error) {
    console.error('❌ Failed to connect to Supabase:', error);
    console.warn('⚠️  Falling back to IN-MEMORY storage');
    useInMemory = true;
    return null;
  }
}

export function isUsingInMemory(): boolean {
  return useInMemory;
}

// Helper to create client with custom auth token (for RLS)
export function getSupabaseClientWithAuth(authToken: string): SupabaseClient<any> {
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    throw new Error('Missing Supabase credentials.');
  }

  return createClient(supabaseUrl, supabaseKey, {
    global: {
      headers: {
        Authorization: `Bearer ${authToken}`,
      },
    },
  });
}

// Type-safe database schema (to be generated by Supabase CLI)
export type { Database };
