// Supabase client configuration
import { createClient, SupabaseClient } from '@supabase/supabase-js';

// TODO: Generate proper types with: supabase gen types typescript --local
// For now, using any to avoid type issues
type Database = any;

let supabaseClient: SupabaseClient<any> | null = null;

export function getSupabaseClient(): SupabaseClient<any> {
  if (supabaseClient) {
    return supabaseClient;
  }

  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    throw new Error(
      'Missing Supabase credentials. Set SUPABASE_URL and SUPABASE_ANON_KEY environment variables.'
    );
  }

  supabaseClient = createClient(supabaseUrl, supabaseKey, {
    auth: {
      persistSession: false, // For server-side usage
      autoRefreshToken: false,
    },
  });

  return supabaseClient;
}

// Helper to create client with custom auth token (for RLS)
export function getSupabaseClientWithAuth(authToken: string): SupabaseClient<any> {
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    throw new Error('Missing Supabase credentials.');
  }

  return createClient(supabaseUrl, supabaseKey, {
    global: {
      headers: {
        Authorization: `Bearer ${authToken}`,
      },
    },
  });
}

// Type-safe database schema (to be generated by Supabase CLI)
export type { Database };
